# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.gitlocalize.com" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: GitLocalize Blog
  avatar: icon.png
  gravatar: # Email MD5 hash
  description: "GitLocalize: Continuous localization platform for GitHub repositories" # used by search engines

  # Header and footer text
  #header_text: >
  #   <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>

  #   <p>Remove all header text in <code>_config.yml</code> to disable this feature.</p>
  #header_text_feature_image:
  #footer_text: >
  # Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: true
  email_address: "contact@gitlocalize.com" # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook: gitlocalize
  flickr:
  github: gitlocalize
  google_plus:
  instagram:
  linkedin: # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange: # Full URL
  steam:
  tumblr:
  twitter: gitlocalize
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-79830225-4"
  disqus_shortname:
  muut_community_name: # From muut.com settings, e.g. "muttcommunityname"
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Read More <small>â†—</small>"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:300,400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-multiple-languages-plugin
languages: ["en", "ja", "ru"]
permalink: /posts/:categories/:title
future: true
